### ISSUE TITLE
Add a new field in BLSample table : filePath

### ISSUE THREAD

**Issue by delageniere** [ispyb/ispyb-database-documentation#26]
This is a request from CRIMS and ID30B, to be able to handle the plates repositioning.
It will be used for example to store an image of the drop.

**Comment by stufisher** [comment]
Can you provide a bit more detail please? It will be an image of the sample from the plate imager?
You should make use of our existing tables for LIMS and put an entry into BLSampleImage

**Comment by drnasmith** [comment]
We owe the group a more detailed description of how we use tables at DLS for plates and images than we covered at the last ISPyB developer meeting.

**Comment by delageniere** [comment]
Following our dev meeting of today, we will use BLSampleImage to store the filePath of the drop image.
