### ISSUE TITLE
Add AxisStart to EnergyScan / XFESpectrum

### ISSUE THREAD

**Issue by stufisher** [ispyb/ispyb-database-documentation#30]
We would like to record axis start position along with EnergyScans / MCAs.

Thus would like to add
AxisStart float to EnergyScan & XFEFluorescenceSpectrum

**Comment by KarlLevik** [comment]
What about axisEnd, axisRange?

**Comment by antolinos** [comment]
It is fine with us

**Comment by stufisher** [comment]
You dont generally do rotation with an xfe scan?

**Comment by KarlLevik** [comment]
@stufisher In that case, isn't 'axisStart' a misleading name? If you have a start, that implies an end, and a range between them ...

**Comment by stufisher** [comment]
its just consistent with other tables. but if you wanna call it axisposition or something then as you like...

**Comment by KarlLevik** [comment]
These changes are now 'live' at Diamond as well, so this issue can be closed.
