### ISSUE TITLE
State of a proposal

### ISSUE THREAD

**Issue by KarlLevik** [ispyb/ispyb-database-documentation#36]
I'd like to propose a `state` column for the `Proposal` table:

```sql
ALTER TABLE Proposal
    ADD state enum('Open', 'Closed', 'Cancelled') NULL DEFAULT 'Open';
```

This way the ISPyB applications can prevent users from e.g. uploading shipments to proposals that are not open.

**Comment by antolinos** [comment]
It is fine with us. Our states are slightly different but not sure how we are going to use it.
